version: '3.1'

services:
  localdb:
    container_name: ${DATABASE_CONTAINER_NAME}
    image: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      DATABASE_CONTAINER_NAME: ${DATABASE_CONTAINER_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PORT: ${LOCAL_DATABASE_PORT}
    ports:
      - ${LOCAL_DATABASE_PORT}:5432 # Default PostgreSQL port